twig:
  default_path: '%kernel.project_dir%/templates'
  paths:
    '%kernel.project_dir%/templates': templates
    '%kernel.project_dir%/vendor/blackknight467/star-rating-bundle/blackknight467/StarRatingBundle/Resources/views': StarRatingBundle
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'

#    form_themes: ['bootstrap_4_layout.html.twig']
