vich_uploader:
    db_driver: orm
    mappings:
        user_pictures:
            uri_prefix: uploads/users
            upload_destination: '%kernel.root_dir%/../public/uploads/users'
        parking_pictures:
            uri_prefix : uploads/parkings
            upload_destination: '%kernel.root_dir%/../public/uploads/parkings'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true